---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false

addons:
  firefox: latest

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+$/
    - /^greenkeeper\/.*$/

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - EMBER_TRY_SCENARIO=ember-lts-2.12
    - EMBER_TRY_SCENARIO=ember-lts-2.16
    - EMBER_TRY_SCENARIO=ember-lts-2.18
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
  include:
    - stage: Deploy
      addons: ignore
      cache: ignore
      env: ignore
      before_install: ignore
      install: ignore
      script: ignore
      deploy:
        provider: npm
        email: kellyselden@gmail.com
        api_key:
          secure: FPySvZZ71HG/MxKhHhIivazbygzvRWLTdtXeVfp07VxQekJ7rXVdG+yo83CHXHqleXXWHcbkOz5Vlqfu9c9M0AP7YozacafoJo9qIw/BAAtfkEmL3UfeGDQZfsFXRa+2e5cMxJraG0PDNpDewM4LAPeuWCYIfu3N+RYbbSRT4hP1nZp5nHXI/CA0uFCfVV+PEAIxbPhAtwUHooU+7ALSNvxk9yiEY2gKk+R02F0bkxtnKEpzrZhzvCeo8pIHHqfWSoj0LCegZ2ckG34RN0rykgIZIwkRv4D07Z9yUVEOvtznNdVzPP7YAOnFQIE/HF5f7UIlBOYYMiKiJeJ4O7E0Wu7bA1eR1DdJANiraXYDgLQ1vZSffBayKCqwDpjQBoZ4mBlMRidYU2GqV6DZdxjdd+Es7jyqt0aFrtKVcLuYsjIZj0eH2Kfsm/UhlPx12Stu9bvu6/tmPyhTIUDvISvdhOj5IAA+rDAhT3c2X3qGrz8m3sjfrbLhp8vSI2cO07CbU2qmuZy8+j1YBb8HUUaN5+O8rkc+hlAWw3bj59UH+wBtvJTNtLdcGrVice/Uv+CqgHO5K7qV2M7AAbujKLDBqpK0DDKtB519I3JRric8uQa58bLPJme6UsD6Q952LjQat23y3PZcgwY/jyhds6lmrmY0wId538UVUymFnTfmSCE=
        on:
          tags: true
          repo: kellyselden/ember-awesome-macros

before_install:
  - npm config set spin false
  - npm install -g npm@5
  - npm --version

script:
  - npm run lint:js
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
